use_frameworks!

target 'Shimmeraiser_Example' do
  pod 'Shimmeraiser', :path => '../'

   target 'Shimmeraiser_ExampleTests' do
       inherit! :search_paths
       pod 'Nimble'
       pod 'Quick'

   end
end
